name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:    [ created ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Lint
      uses: golangci/golangci-lint-action@v2.5.2
      
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v ./...

  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
