name: Release

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm64]
        exclude:  
          - goarch: "386"
            goos: darwin 
          - goarch: arm64
            goos: windows 
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.16.linux-amd64.tar.gz"
        project_path: "./cmd/test-binary"
        binary_name: "trouxa"
        extra_files: LICENSE README.md
